ALTER TABLE "ImapConfig" ADD COLUMN "smtpHost" TEXT NOT NULL DEFAULT 'smtp.titan.email';
ALTER TABLE "ImapConfig" ADD COLUMN "smtpPort" INTEGER NOT NULL DEFAULT 465;
ALTER TABLE "ImapConfig" ADD COLUMN "lastSyncEmailCount" INTEGER NOT NULL DEFAULT 0;
